### ISSUE TITLE
Notification box margin issues

### ISSUE THREAD

**Issue by Ozmodiar** [Clastic/Clastic#32] opened 2015-01-09 11:34 UTC
https://www.dropbox.com/s/etvztitrc9tzkx4/Screenshot%202015-01-09%2012.33.47.png?dl=0

There are some margin issues (left and bottom) when the notification box is shown. Tested in Chrome.

**Comment by NoUseFreak** [comment] 2015-01-10 12:26
Duplicate of #17

**Closed by NoUseFreak** 2015-01-10 12:26 UTC
